-- MySQL Script generated by MySQL Workbench
-- Thu May 18 17:12:42 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema enjoytrip
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema enjoytrip
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `enjoytrip` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `enjoytrip` ;

-- -----------------------------------------------------
-- Table `enjoytrip`.`board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enjoytrip`.`board` (
  `article_no` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `subject` VARCHAR(200) NOT NULL,
  `content` VARCHAR(2000) NULL DEFAULT NULL,
  `hit` INT UNSIGNED NOT NULL DEFAULT '0',
  `register_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`article_no`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `enjoytrip`.`hotplace`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enjoytrip`.`hotplace` (
  `article_no` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `subject` VARCHAR(200) NOT NULL,
  `content` VARCHAR(2000) NULL DEFAULT NULL,
  `hit` INT UNSIGNED NOT NULL DEFAULT '0',
  `likes` INT UNSIGNED NOT NULL DEFAULT '0',
  `register_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `content_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`article_no`),
  INDEX `hotplace_to_attraction_info_content_id_fk` (`content_id` ASC) VISIBLE,
  CONSTRAINT `hotplace_to_attraction_info_content_id_fk`
    FOREIGN KEY (`content_id`)
    REFERENCES `enjoytrip`.`attraction_info` (`content_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `enjoytrip`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enjoytrip`.`comment` (
  `comment_no` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `article_no` INT UNSIGNED NOT NULL,
  `user_id` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `content` VARCHAR(2000) NULL DEFAULT NULL,
  `register_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`comment_no`),
  INDEX `comment_to_hotplace_article_no_fk` (`article_no` ASC) VISIBLE,
  CONSTRAINT `comment_to_hotplace_article_no_fk`
    FOREIGN KEY (`article_no`)
    REFERENCES `enjoytrip`.`hotplace` (`article_no`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `enjoytrip`.`notice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enjoytrip`.`notice` (
  `article_no` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `subject` VARCHAR(200) NOT NULL,
  `content` VARCHAR(2000) NULL DEFAULT NULL,
  `hit` INT UNSIGNED NOT NULL DEFAULT '0',
  `register_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`article_no`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `enjoytrip`.`tripplan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enjoytrip`.`tripplan` (
  `article_no` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `subject` VARCHAR(200) NOT NULL,
  `content` VARCHAR(2000) NULL DEFAULT NULL,
  `hit` INT UNSIGNED NOT NULL DEFAULT '0',
  `likes` INT UNSIGNED NOT NULL DEFAULT '0',
  `register_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`article_no`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `enjoytrip`.`tripplan_attraction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enjoytrip`.`tripplan_attraction` (
  `tpa_id` INT NOT NULL AUTO_INCREMENT,
  `article_no` INT NULL DEFAULT NULL,
  `content_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`tpa_id`),
  INDEX `tripplan_to_attraction_info_content_id_fk_idx` (`content_id` ASC) VISIBLE,
  INDEX `tripplan_attraction_to_tripplan_article_no_fk_idx` (`article_no` ASC) VISIBLE,
  CONSTRAINT `tripplan_attraction_to_attraction_info_content_id_fk`
    FOREIGN KEY (`content_id`)
    REFERENCES `enjoytrip`.`attraction_info` (`content_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `tripplan_attraction_to_tripplan_article_no_fk`
    FOREIGN KEY (`article_no`)
    REFERENCES `enjoytrip`.`tripplan` (`article_no`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `enjoytrip`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enjoytrip`.`user` (
  `id` VARCHAR(20) NOT NULL,
  `pass` VARCHAR(100) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `position` VARCHAR(30) NOT NULL DEFAULT 'user',
  `token` VARCHAR(1000) DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `enjoytrip`.`like_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enjoytrip`.`like_list` (
  `llist_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(20) NOT NULL,
  `article_no` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`llist_id`),
  INDEX `like_list_to_hotplace_article_no_idx` (`article_no` ASC) VISIBLE,
  INDEX `like_list_to_user_id_idx` (`id` ASC) VISIBLE,
  CONSTRAINT `like_list_to_hotplace_article_no`
    FOREIGN KEY (`article_no`)
    REFERENCES `enjoytrip`.`hotplace` (`article_no`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `like_list_to_user_id`
    FOREIGN KEY (`id`)
    REFERENCES `enjoytrip`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
